# Generated by Django 4.2 on 2023-04-11 17:46

import Locations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=Locations.models.upload_to),
        ),
    ]
