# Generated by Django 4.2 on 2023-04-13 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Locations', '0002_location_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='Location',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
