# Generated by Django 4.2 on 2023-04-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0004_locationhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationhistory',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='locationhistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
